(()=>{
'use strict';
const $=s=>document.querySelector(s),canvas=$('#canvas'),ctx=canvas.getContext('2d'),screens=['intro','countdown','over','modal','skinsModal','settingsModal','installModal'],colors=['#d9ff43','#52e5ff','#ff4ea3','#9b7bff'],pad=n=>Math.max(0,n|0).toString().padStart(4,'0');
const track=(event,params={})=>{if(typeof window.gtag==='function')window.gtag('event',event,params)};
let state='intro',W=0,H=0,dpr=1,last=performance.now(),score=0,lives=3,best=+(localStorage.ndBest||0),inv=0,shake=0,drag=false,startX=0,startTarget=0,target=0,combo=0,maxCombo=0,perfects=0,passed=0,rush=0,rushLevel=0,doublePoints=0,wideGates=0,nextRiskAt=11,nextMysteryAt=24,nextChainAt=18,chainLeft=0,chainStep=0,speedBurst=0,recoveryGates=0,nextSpeedBurstAt=28,nextBossAt=50,bossLeft=0,bossMirror=false,bossFailed=false,maxRushCounted=false,comboShield=false,streakFlash=0,streakPulse=0,statusUntil=0,rng=Math.random,player={x:0,y:0,r:12},gates=[],parts=[],trail=[],audio=null,music=null,musicStep=0,muted=localStorage.ndMuted==='1',deferredInstall=null,timers=[],careerPerfects=+(localStorage.ndPerfects||0),careerRisks=+(localStorage.ndRisks||0),careerMysteries=+(localStorage.ndMysteries||0),careerMaxRushes=+(localStorage.ndMaxRushCount||(localStorage.ndMaxRush==='1'?1:0)),selectedSkin=localStorage.ndSkin||'core',mastery=(()=>{try{return JSON.parse(localStorage.ndMastery||'{}')}catch{return{}}})();
const hapticSupported=typeof navigator.vibrate==='function';let haptics=hapticSupported&&localStorage.ndHaptic!=='0',shakeEnabled=localStorage.ndShake!=='0',flashesEnabled=localStorage.ndFlashes!=='0',settingsReturn='intro',settingsPausedGame=false,updatePending=false,refreshing=false,swRegistration=null;
const renderSettings=()=>{$('#sound').innerHTML=`SOUND <span>${muted?'OFF':'ON'}</span>`;$('#sound').setAttribute('aria-pressed',String(!muted));$('#haptic').innerHTML=`HAPTIC <span>${haptics?'ON':'OFF'}</span>`;$('#haptic').setAttribute('aria-pressed',String(haptics));$('#haptic').style.display=hapticSupported?'flex':'none';$('#shakeToggle').innerHTML=`SCREEN SHAKE <span>${shakeEnabled?'ON':'OFF'}</span>`;$('#shakeToggle').setAttribute('aria-pressed',String(shakeEnabled));$('#flashToggle').innerHTML=`FLASH EFFECTS <span>${flashesEnabled?'ON':'OFF'}</span>`;$('#flashToggle').setAttribute('aria-pressed',String(flashesEnabled));document.querySelector('.game').classList.toggle('flashes-off',!flashesEnabled)};
$('#best').textContent=pad(best);$('#name').value=localStorage.ndName||'PLAYER';renderSettings();
function applyUpdate(force=false){if(updatePending&&!refreshing&&(force||state==='intro')){refreshing=true;location.reload()}}
const show=id=>{screens.forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));state=id;if(id==='intro')setTimeout(()=>applyUpdate(),0)};
const tone=(f,d=.1,v=.03,type='sine')=>{if(muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain(),n=audio.currentTime;o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(v,n+.012);g.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(g).connect(audio.destination);o.start();o.stop(n+d+.02)};
const vibrate=p=>{if(!haptics||!hapticSupported)return false;const pulse=Array.isArray(p)?p.map((n,i)=>i%2?n:Math.max(22,n)):Math.max(22,p);try{return navigator.vibrate.call(navigator,pulse)}catch{return false}};
const startMusic=()=>{if(muted)return;try{const AudioEngine=window.AudioContext||window.webkitAudioContext;if(!AudioEngine)return;audio||=new AudioEngine();audio.resume().catch(()=>{});if(music)return;const notes=[220,277,330,415,330,277,247,330];music=setInterval(()=>{tone(notes[musicStep%8]*(rush>0?2:1),.16,rush>0?.026:.016,musicStep%4?'sine':'triangle');musicStep++},210)}catch{audio=null}};
const makeGate=(y,i)=>{const progress=Math.min(passed,45),breath=i%7===6;if(!bossLeft&&i>=nextBossAt){bossLeft=5;bossMirror=Math.random()<.5;bossFailed=false;nextBossAt=i+50}const boss=bossLeft>0,bossIndex=boss?5-bossLeft:-1,mystery=!boss&&i>=nextMysteryAt,risk=!boss&&!mystery&&i>=nextRiskAt,boost=wideGates>0?1.3:1;let gapW=Math.min(W-44,Math.max(boss?108:risk?126:112,W*(boss?.37:risk?.36:mystery?.43:breath?.52:.47-progress*.0048))*boost),margin=22,position=Math.random();if(!boss&&!mystery&&!risk&&!chainLeft&&i>=nextChainAt){chainLeft=3;chainStep=Math.random()<.5?0:2}const chain=!boss&&!mystery&&!risk&&chainLeft>0;let gapX=i<2?W/2-gapW/2:margin+position*(W-gapW-margin*2),riskX=0,riskW=0;if(boss){const pattern=bossMirror?[2,0,1,2,0]:[0,2,1,0,2],slots=[margin,W/2-gapW/2,W-margin-gapW];gapX=slots[pattern[bossIndex]];bossLeft--}if(chain){const slots=[margin,W/2-gapW/2,W-margin-gapW],slot=(chainStep+(3-chainLeft))%3;gapX=slots[slot];chainLeft--;if(!chainLeft)nextChainAt=i+14+Math.floor(Math.random()*8)}if(mystery)nextMysteryAt=i+20+Math.floor(Math.random()*11);if(risk){const normalLeft=Math.random()<.5;gapX=normalLeft?margin:W-margin-gapW;riskW=Math.max(48,W*.13);riskX=normalLeft?W-margin-riskW:margin;nextRiskAt=i+10+Math.floor(Math.random()*7)}const moving=!boss&&!chain&&!risk&&!mystery&&i>=18&&Math.random()<Math.min(.3,.13+(i-18)*.004),shrinking=!boss&&!chain&&!risk&&!mystery&&!moving&&i>=24&&Math.random()<.18,precision=!risk&&!mystery&&i>=16&&Math.random()<.3,moveAmp=moving?Math.min(38,W*.085):0;return{y,gapX,gapW,initialGapW:gapW,baseGapX:gapX,moving,shrinking,precision,moveAmp,moveSpeed:.0011+Math.random()*.00055,phase:Math.random()*Math.PI*2,chain,boss,bossIndex,risk,mystery,riskX,riskW,done:false,c:boss?'#ff4ea3':mystery?'#b44cff':colors[i%4],i}};
const reset=()=>{player={x:W/2,y:H*.34,r:Math.max(11,W*.03)};target=W/2;gates=[];for(let i=0;i<7;i++)gates.push(makeGate(H*(.72+i*.18),i));parts=[];inv=0;drag=false};
const resize=()=>{dpr=Math.min(2,devicePixelRatio||1);W=canvas.clientWidth;H=canvas.clientHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);if(state!=='playing')reset();else{player.x=Math.max(player.r,Math.min(W-player.r,player.x));target=Math.max(player.r,Math.min(W-player.r,target))}};
const burst=(x,y,c,n=12)=>{for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=45+Math.random()*150;parts.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.5,c})}};
const setStatus=(text,duration=700,color='#52e5ff')=>{const el=$('#gameStatus');el.textContent=text;el.style.color=color;statusUntil=performance.now()+duration};
const feedback=(text,perfect=false)=>{if(text.includes('RUSH'))track('rush_reached',{rush_name:text,combo,score});if(text==='RISK +10')track('risk_gate_taken',{combo,score});if(text==='PERFECT'){streakPulse=Math.max(streakPulse,.18);return}const bossOnScreen=gates.some(g=>g.boss&&!g.done),major=text.startsWith('BOSS CLEAR')||(text==='MAX RUSH'&&combo===20&&!speedBurst&&!bossOnScreen);if(!major){setStatus(text,text==='COMBO LOST'?900:720,perfect?'#d9ff43':text==='COMBO LOST'?'#ff4ea3':'#f4f0e6');return}const el=$('#feedback');el.textContent=text;el.style.color=perfect?'#d9ff43':'#f4f0e6';el.classList.remove('pop');void el.offsetWidth;el.classList.add('pop')};
const drawGateSegments=(gate,y,height)=>{const openings=[{x:gate.gapX,w:gate.gapW}];if(gate.risk)openings.push({x:gate.riskX,w:gate.riskW});openings.sort((a,b)=>a.x-b.x);let edge=0;for(const opening of openings){if(opening.x>edge)ctx.fillRect(edge,y,opening.x-edge,height);edge=Math.max(edge,opening.x+opening.w)}if(edge<W)ctx.fillRect(edge,y,W-edge,height)};
const drawWorld=now=>{const zone=score<30?0:score<70?1:score<120?2:3,background=['#100e18','#071923','#130b19','#030306'][zone];ctx.fillStyle=rush>0?'#171023':background;ctx.fillRect(0,0,W,H);if(zone===0){ctx.globalAlpha=.13;ctx.strokeStyle='#9b7bff';for(let x=0;x<W;x+=44){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=-(now*.025%44);y<H;y+=44){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}else if(zone===1){ctx.globalAlpha=.18;ctx.strokeStyle='#52e5ff';for(let x=-W;x<W*2;x+=58){ctx.beginPath();ctx.moveTo(W/2,H*.35);ctx.lineTo(x,H);ctx.stroke()}for(let y=-(now*.05%54);y<H;y+=54){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}else if(zone===2){ctx.globalAlpha=.11;ctx.fillStyle='#ff4ea3';for(let i=0;i<22;i++){const x=(i*83)%Math.max(W,1),y=(i*137)%Math.max(H,1);ctx.fillRect(x,y,2,2)}}else{ctx.globalAlpha=.35;ctx.fillStyle='#f4f0e6';for(let i=0;i<34;i++){const x=(i*97)%Math.max(W,1),y=(i*151+now*.045*(1+i%3))%Math.max(H,1);ctx.fillRect(x,y,1+i%2,5+i%4)}}ctx.globalAlpha=1};
const rushName=level=>level>=4?'MAX RUSH':level===3?'ULTRA RUSH':level===2?'SUPER RUSH':'NEON RUSH';
const updateCombo=()=>{const base=Math.min(5,1+Math.floor(combo/2)),boost=rush>0?Math.min(5,rushLevel+1):1;$('#multiplier').textContent='X'+base*boost;$('#comboText').textContent=combo+' PERFECT';$('#combo').classList.toggle('on',combo>=2);$('#rush').classList.toggle('on',rush>0)};
const updateGameStatus=now=>{if(state!=='playing'){$('#gameStatus').textContent='';return}if(now<statusUntil)return;const bossGate=gates.filter(g=>g.boss&&!g.done&&g.y>player.y-player.r).sort((a,b)=>a.y-b.y)[0],el=$('#gameStatus');let text='',color='#52e5ff';if(bossGate){text=`BOSS ${bossGate.bossIndex+1} / 5`;color='#ff4ea3'}else if(speedBurst>0){text=`SPEED BURST · ${speedBurst}`;color='#ff4ea3'}else if(recoveryGates>0)text='BREATHE';else if(doublePoints>0){text='X2 SCORE';color='#d9ff43'}else if(wideGates>0)text='WIDE GATES';else if(comboShield){text='SHIELD READY';color='#52e5ff'}else if(rush>0){text=rushName(rushLevel);color='#d9ff43'}el.textContent=text;el.style.color=color};
const renderLives=()=>{$('#lives').textContent='● '.repeat(Math.max(0,lives))+'○ '.repeat(Math.max(0,3-lives))};
const skinList=()=>[
  {id:'core',name:'Neon Core',orb:'#f4f0e6',glow:'#d9ff43',open:true,current:1,target:1,rule:'AVAILABLE'},
  {id:'plasma',name:'Plasma Ball',orb:'#52e5ff',glow:'#ff4ea3',open:careerPerfects>=150,current:careerPerfects,target:150,rule:'TOTAL PERFECTS'},
  {id:'gold',name:'Gold Core',orb:'#ffd84a',glow:'#ffd84a',open:careerRisks>=40,current:careerRisks,target:40,rule:'RISK GATES TAKEN'},
  {id:'void',name:'Void Ball',orb:'#171023',glow:'#9b7bff',open:best>=2500,current:best,target:2500,rule:'PERSONAL BEST'},
  {id:'rainbow',name:'Rainbow Ball',orb:'#ff4ea3',glow:'#52e5ff',open:careerMaxRushes>=3,current:careerMaxRushes,target:3,rule:'MAX RUSH RUNS'},
  {id:'mystic',name:'Mystic Orb',orb:'#b44cff',glow:'#d9ff43',open:careerMysteries>=12,current:careerMysteries,target:12,rule:'MYSTERY GATES'}
];
const unlockedSkins=()=>skinList().filter(s=>s.open);
const masteryCount=id=>+(mastery[id]||0),masteryTier=id=>masteryCount(id)>=1500?2:masteryCount(id)>=500?1:0;
const addMastery=()=>{mastery[selectedSkin]=masteryCount(selectedSkin)+1;localStorage.ndMastery=JSON.stringify(mastery)};
const masteryLabel=id=>{const n=masteryCount(id);return n>=1500?'MASTERED · SPECIAL MOTION':n>=500?`${n} / 1500 · ANIMATED TRAIL`:`${n} / 500 · STRONGER TRAIL`};
const renderSkins=()=>{const list=skinList();if(!list.some(s=>s.id===selectedSkin&&s.open)){selectedSkin='core';localStorage.ndSkin='core'}$('#skinGrid').innerHTML=list.map(s=>{const count=masteryCount(s.id),masteryTarget=count>=500?1500:500,current=s.open?Math.min(count,masteryTarget):Math.min(s.current,s.target),target=s.open?masteryTarget:s.target,progress=count>=1500&&s.open?100:Math.round(current/target*100);return`<button class="skin-card ${s.open?'':'locked'} ${s.id===selectedSkin?'selected':''}" data-skin="${s.id}" ${s.open?'':'disabled'} style="--orb:${s.orb};--glow:${s.glow};--progress:${progress}%"><span class="skin-state">${s.open?'MASTERY '+masteryTier(s.id)+'/2':'LOCKED'}</span><span class="skin-orb"></span><b>${s.name}</b><small>${s.open?masteryLabel(s.id):`${current} / ${s.target} · ${s.rule}`}</small><span class="skin-meter"><i></i></span></button>`}).join('');$('#skinProgress').textContent=`UNLOCKED ${unlockedSkins().length} / ${list.length}`;$('#skinGrid').querySelectorAll('[data-skin]:not([disabled])').forEach(button=>button.onclick=()=>{selectedSkin=button.dataset.skin;localStorage.ndSkin=selectedSkin;trail=[];track('ball_skin_selected',{skin:selectedSkin});renderSkins()})};
const mysteryReward=()=>{const reward=Math.floor(Math.random()*4);if(reward===0){const bonus=25*(doublePoints>0?2:1);score+=bonus;feedback('BONUS +'+bonus,true)}else if(reward===1){doublePoints=10;feedback('DOUBLE SCORE',true)}else if(reward===2){wideGates=10;for(const gate of gates){if(!gate.done){const center=gate.gapX+gate.gapW/2;gate.gapW=Math.min(W-44,gate.gapW*1.3);gate.gapX=Math.max(22,Math.min(W-22-gate.gapW,center-gate.gapW/2));gate.initialGapW=gate.gapW;gate.baseGapX=gate.gapX}}feedback('WIDE GATES',true)}else{combo=Math.max(combo,5);rushLevel=Math.max(rushLevel,1);rush=10;feedback('INSTANT RUSH',true);updateCombo()}const names=['score_bonus','double_score','wide_gates','instant_rush'];track('mystery_gate_reward',{reward:names[reward],score});tone(920+reward*110,.28,.055,'triangle');vibrate([18,28,18]);return names[reward]};
const scores=()=>{try{return JSON.parse(localStorage.ndTop||'[]')}catch{return[]}};
const boardHTML=()=>{const list=scores();return'<h2><span>TOP 10</span><span>THIS DEVICE</span></h2>'+(list.length?list.map((r,i)=>`<div class="row"><span>${i+1}.</span><span>${r.name}</span><b>${pad(r.score)}</b></div>`).join(''):'<p class="copy">Play your first run to enter the board.</p>')};
const renderBoards=()=>{$('#fullBoard').innerHTML=boardHTML()};
const save=()=>{const old=best;best=Math.max(best,score);localStorage.ndBest=best;$('#best').textContent=pad(best);const name=localStorage.ndName||'PLAYER',list=[...scores(),{name,score,date:Date.now()}].sort((a,b)=>b.score-a.score||a.date-b.date).slice(0,10);localStorage.ndTop=JSON.stringify(list);renderBoards();return score>old};
const finish=()=>{if(state!=='playing')return;shake=14;rush=0;rushLevel=0;updateCombo();burst(player.x,player.y,'#ff4ea3',32);tone(95,.42,.05,'sawtooth');vibrate([30,35,70]);const record=save();$('#result').textContent=pad(score);$('#resultText').textContent=record?'NEW PERSONAL BEST':Math.max(1,best-score)+' POINTS FROM YOUR BEST';$('#resultText').classList.toggle('new-record',record);$('#perfectStat').textContent=perfects;$('#comboStat').textContent=maxCombo;$('#gateStat').textContent=passed;show('over')};
const hit=g=>{g.done=true;if(g.boss)bossFailed=true;shake=9;burst(player.x,g.y,'#ff4ea3',20);lives--;const hadCombo=combo>=2;combo=0;comboShield=false;rush=0;rushLevel=0;updateCombo();renderLives();if(hadCombo)feedback('COMBO LOST');tone(130,.2,.05,'square');vibrate(60);if(lives<=0)finish();else inv=1.05};
const celebrateStreak=()=>{if(![10,20,30,50].includes(combo))return;streakFlash=.55;streakPulse=.7;const step={10:0,20:1,30:2,50:3}[combo];tone(980+step*150,.16,.045+step*.008,step>1?'sawtooth':'triangle');setTimeout(()=>tone(1240+step*170,.12,.035,'sine'),70);vibrate(step>1?[12,20,18]:12);track('perfect_streak',{milestone:combo,skin:selectedSkin})};
const advanceChallenge=()=>{if(speedBurst>0){speedBurst--;if(!speedBurst)recoveryGates=2}else if(recoveryGates>0)recoveryGates--;else if(passed>=nextSpeedBurstAt&&!gates.some(g=>(g.chain||g.boss)&&!g.done)){speedBurst=3;nextSpeedBurstAt=passed+18+Math.floor(Math.random()*10);streakFlash=.42;tone(720,.12,.032,'triangle');setTimeout(()=>tone(920,.1,.028,'triangle'),80);track('speed_burst_started',{score,passed})}};
const pass=(g,tookRisk=false)=>{g.done=true;passed++;addMastery();advanceChallenge();const factor=doublePoints>0?2:1;if(g.mystery){careerMysteries++;localStorage.ndMysteries=careerMysteries;score+=factor;mysteryReward();burst(player.x,g.y,'#b44cff',28);$('#score').textContent=pad(score);return}const center=g.gapX+g.gapW/2,precisionHit=g.precision&&!tookRisk&&Math.abs(player.x-center)<=Math.max(5,g.gapW*.035),isPerfect=tookRisk||Math.abs(player.x-center)<=Math.max(12,g.gapW*.1);if(isPerfect){combo++;perfects++;careerPerfects++;localStorage.ndPerfects=careerPerfects;maxCombo=Math.max(maxCombo,combo);if(combo===15)comboShield=true;celebrateStreak();if(tookRisk){careerRisks++;localStorage.ndRisks=careerRisks}const mult=Math.min(5,1+Math.floor(combo/2));if(combo%5===0){rushLevel=Math.min(4,combo/5);rush=Math.min(12,8+rushLevel);if(rushLevel===4&&!maxRushCounted){maxRushCounted=true;careerMaxRushes++;localStorage.ndMaxRushCount=careerMaxRushes}const label=rushName(rushLevel);feedback(label,true);tone(820+rushLevel*90,.3,.06,'sawtooth');vibrate([18,22,18,22,28])}else{feedback(tookRisk?'RISK +10':precisionHit?'PRECISION +6':'PERFECT',true);tone(tookRisk?980:precisionHit?1080:600+Math.min(combo,8)*55,.1,tookRisk||precisionHit?.05:.036,'square');vibrate(tookRisk?[16,18,28]:precisionHit?[10,14,18]:12)}const boost=rush>0?Math.min(5,rushLevel+1):1;score+=(mult*boost+(tookRisk?10:0)+(precisionHit?6:0))*factor;burst(player.x,g.y,precisionHit?'#f4f0e6':tookRisk?'#ffd84a':g.c,rush>0?20+rushLevel*4:precisionHit?18:13);if(precisionHit)track('precision_core_hit',{score,combo})}else if(comboShield){comboShield=false;score+=factor;streakFlash=.35;streakPulse=.45;tone(760,.16,.04,'triangle');vibrate([10,22,10]);burst(player.x,g.y,'#52e5ff',16);track('combo_shield_used',{combo,score})}else{const hadCombo=combo>=2;combo=0;rush=0;rushLevel=0;score+=factor;if(hadCombo)feedback('COMBO LOST');tone(470,.075,.022);burst(player.x,g.y,g.c,7)}if(g.boss&&g.bossIndex===4&&!bossFailed){score+=50*factor;streakFlash=.7;feedback('BOSS CLEAR +'+50*factor,true);tone(1180,.24,.06,'sawtooth');burst(player.x,g.y,'#d9ff43',34);track('boss_sequence_cleared',{score})}$('#score').textContent=pad(score);updateCombo()};
const clearTimers=()=>{timers.forEach(clearTimeout);timers=[]};
const begin=(fast=false)=>{const name=$('#name').value.toUpperCase().replace(/[^A-Z0-9_]/g,'').slice(0,12)||'PLAYER';localStorage.ndName=name;$('#name').value=name;startMusic();tone(440,.12,.04,'square');clearTimers();score=0;lives=3;combo=0;maxCombo=0;perfects=0;passed=0;rush=0;rushLevel=0;doublePoints=0;wideGates=0;maxRushCounted=false;comboShield=false;streakFlash=0;streakPulse=0;statusUntil=0;$('#gameStatus').textContent='';trail=[];chainLeft=0;chainStep=0;speedBurst=0;recoveryGates=0;bossLeft=0;bossFailed=false;nextRiskAt=10+Math.floor(Math.random()*5);nextMysteryAt=20+Math.floor(Math.random()*11);nextChainAt=18+Math.floor(Math.random()*6);nextSpeedBurstAt=28+Math.floor(Math.random()*7);nextBossAt=50;$('#score').textContent='0000';renderLives();$('#combo').classList.remove('on');$('#rush').classList.remove('on');$('#hint').classList.add('hidden');reset();show('countdown');const el=$('#count');if(fast){el.textContent='GO!';timers.push(setTimeout(()=>{show('none');state='playing'},420));return}const showTutorial=localStorage.ndTutorialSeen!=='1';el.textContent='3';timers.push(setTimeout(()=>el.textContent='2',500),setTimeout(()=>el.textContent='1',1000),setTimeout(()=>el.textContent='GO!',1500),setTimeout(()=>{show('none');state='playing';if(showTutorial){$('#hint').classList.remove('hidden');localStorage.ndTutorialSeen='1'}},1800),setTimeout(()=>$('#hint').classList.add('hidden'),5000))};
canvas.addEventListener('pointerdown',e=>{if(state!=='playing')return;drag=true;startX=e.clientX;startTarget=target;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(drag)target=Math.max(player.r,Math.min(W-player.r,startTarget+(e.clientX-startX)*1.02))});canvas.addEventListener('pointerup',e=>{drag=false;canvas.hasPointerCapture(e.pointerId)&&canvas.releasePointerCapture(e.pointerId)});canvas.addEventListener('pointercancel',()=>drag=false);
const installed=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;if(!installed)$('#install').hidden=false;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;if(!installed)$('#install').hidden=false});addEventListener('appinstalled',()=>{$('#install').hidden=true;deferredInstall=null});const installHelp=()=>{const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);$('#installStepOne').textContent=ios?'Tap the Share button in Safari.':'Open your browser menu.';$('#installStepTwo').textContent=ios?'Choose “Add to Home Screen”.':'Choose “Install app” or “Add to Home screen”.';show('installModal')};$('#install').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();const choice=await deferredInstall.userChoice;if(choice.outcome==='accepted')$('#install').hidden=true;deferredInstall=null}else installHelp()};
const closeSettingsMenu=()=>{if(settingsPausedGame){show('none');state='playing';last=performance.now()}else show(screens.includes(settingsReturn)&&settingsReturn!=='settingsModal'?settingsReturn:'intro');settingsPausedGame=false};
$('#play').onclick=()=>begin();$('#again').onclick=()=>begin(true);$('#home').onclick=()=>show('intro');$('#top').onclick=()=>show('modal');$('#skins').onclick=()=>{renderSkins();show('skinsModal')};$('#close').onclick=()=>show('intro');$('#closeSkins').onclick=()=>show('intro');$('#closeInstall').onclick=$('#installDone').onclick=()=>show('intro');$('#settings').onclick=()=>{if(state==='settingsModal'){closeSettingsMenu();return}if(state==='countdown')return;settingsPausedGame=state==='playing';settingsReturn=state;renderSettings();show('settingsModal')};$('#closeSettings').onclick=closeSettingsMenu;$('#sound').onclick=()=>{muted=!muted;localStorage.ndMuted=muted?'1':'0';renderSettings();if(!muted){startMusic();tone(660,.1,.04,'square')}};$('#haptic').onclick=()=>{if(!hapticSupported)return;haptics=!haptics;localStorage.ndHaptic=haptics?'1':'0';renderSettings();if(haptics)vibrate([45,30,65])};$('#share').onclick=async()=>{const text=`I scored ${score} with a ${maxCombo} Perfect combo in NEON DROP. Beat me!`;navigator.share?await navigator.share({title:'NEON DROP',text,url:location.href}):await navigator.clipboard.writeText(`${text} ${location.href}`)};
$('#shakeToggle').onclick=()=>{shakeEnabled=!shakeEnabled;localStorage.ndShake=shakeEnabled?'1':'0';if(!shakeEnabled)shake=0;renderSettings()};
$('#flashToggle').onclick=()=>{flashesEnabled=!flashesEnabled;localStorage.ndFlashes=flashesEnabled?'1':'0';if(!flashesEnabled)streakFlash=0;renderSettings()};
const drawTrail=now=>{const tier=masteryTier(selectedSkin),strength=tier?1:.55;ctx.save();trail.forEach((p,i)=>{const age=(i+1)/trail.length,a=age*.38*strength,size=player.r*(.25+age*.5);ctx.globalAlpha=a;if(selectedSkin==='plasma'){ctx.strokeStyle=i%2?'#52e5ff':'#ff4ea3';ctx.lineWidth=1+tier;ctx.beginPath();ctx.moveTo(p.x-5,p.y);ctx.lineTo(p.x+(i%2?6:-6),p.y+5);ctx.stroke()}else if(selectedSkin==='gold'){ctx.fillStyle=i%2?'#ffd84a':'#fff2a6';ctx.fillRect(p.x+(i%3-1)*7,p.y+(i%2?5:-5),2+tier,2+tier)}else if(selectedSkin==='void'){ctx.fillStyle=i%2?'#171023':'#5b2b82';ctx.beginPath();ctx.arc(p.x,p.y,size,0,Math.PI*2);ctx.fill()}else if(selectedSkin==='rainbow'){ctx.fillStyle=`hsl(${(now*.16+i*22)%360} 100% 62%)`;ctx.beginPath();ctx.arc(p.x,p.y,size*.7,0,Math.PI*2);ctx.fill()}else if(selectedSkin==='mystic'){ctx.save();ctx.strokeStyle=i%2?'#b44cff':'#d9ff43';ctx.lineWidth=1+tier*.5;ctx.translate(p.x,p.y);ctx.rotate(Math.PI/4+now*.0004);ctx.strokeRect(-size*.45,-size*.45,size*.9,size*.9);ctx.restore()}else{ctx.fillStyle='#d9ff43';ctx.beginPath();ctx.arc(p.x,p.y,size*.65,0,Math.PI*2);ctx.fill()}});ctx.restore()};
const drawBall=now=>{const skin=skinList().find(s=>s.id===selectedSkin&&s.open)||skinList()[0],tier=masteryTier(skin.id),rainbow=skin.id==='rainbow',pulse=1+(streakPulse>0?Math.sin(now*.04)*.13:0)+(tier===2?Math.sin(now*.006)*.05:0),radius=player.r*pulse,fill=rainbow?`hsl(${now*.16%360} 100% 68%)`:skin.orb,glow=rainbow?`hsl(${(now*.16+100)%360} 100% 62%)`:skin.glow;ctx.globalAlpha=inv>0&&Math.floor(now/90)%2?.25:1;ctx.shadowBlur=rush>0?38:28+tier*7;ctx.shadowColor=rush>0?'#52e5ff':glow;ctx.fillStyle=fill;ctx.beginPath();ctx.arc(player.x,player.y,radius,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(skin.id==='void'){ctx.lineWidth=2;ctx.strokeStyle='#52e5ff';ctx.stroke()}if(tier===2){ctx.strokeStyle=glow;ctx.lineWidth=1.5;ctx.globalAlpha=.55;ctx.beginPath();ctx.arc(player.x,player.y,radius+5+Math.sin(now*.008)*2,now*.002,now*.002+Math.PI*1.45);ctx.stroke()}if(comboShield){ctx.strokeStyle='#52e5ff';ctx.lineWidth=2.5;ctx.globalAlpha=.9;ctx.shadowBlur=12;ctx.shadowColor='#52e5ff';ctx.beginPath();ctx.arc(player.x,player.y,radius+8,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0}ctx.globalAlpha=1;ctx.fillStyle=skin.id==='gold'?'#171023':skin.id==='plasma'?'#f4f0e6':rainbow?'#ffffff':'#ff4ea3';ctx.fillRect(player.x-3,player.y-3,6,6)};
const loop=now=>{
  const dt=Math.min(.033,(now-last)/1000);last=now;
  if(state==='playing'){
    inv=Math.max(0,inv-dt);rush=Math.max(0,rush-dt);doublePoints=Math.max(0,doublePoints-dt);wideGates=Math.max(0,wideGates-dt);streakFlash=Math.max(0,streakFlash-dt);streakPulse=Math.max(0,streakPulse-dt);
    if(!rush&&$('#rush').classList.contains('on'))updateCombo();
    player.x+=(target-player.x)*Math.min(1,dt*11);trail.push({x:player.x,y:player.y});const trailMax=masteryTier(selectedSkin)===2?22:masteryTier(selectedSkin)===1?16:10;if(trail.length>trailMax)trail.splice(0,trail.length-trailMax);
    const wave=(passed%7)/7,breath=passed>0&&passed%7===6,speed=Math.min(272,94+passed*3.15+(wave>.55?16:0)-(breath?24:0)+(speedBurst>0?46:0)-(recoveryGates>0?28:0));
    for(const g of gates){if(g.moving&&!g.done)g.gapX=Math.max(22,Math.min(W-22-g.gapW,g.baseGapX+Math.sin(now*g.moveSpeed+g.phase)*g.moveAmp));if(g.shrinking&&!g.done){const proximity=Math.max(0,Math.min(1,1-(g.y-player.y)/(H*.58))),center=g.baseGapX+g.initialGapW/2;g.gapW=g.initialGapW*(1-proximity*.24);g.gapX=Math.max(22,Math.min(W-22-g.gapW,center-g.gapW/2))}const py=g.y;g.y-=speed*dt;if(!g.done&&py>player.y+player.r&&g.y<=player.y+player.r){const safeNormal=player.x-player.r>=g.gapX&&player.x+player.r<=g.gapX+g.gapW,safeRisk=g.risk&&player.x-player.r>=g.riskX&&player.x+player.r<=g.riskX+g.riskW;if(safeNormal||safeRisk)pass(g,safeRisk);else if(inv<=0)hit(g)}}
    gates=gates.filter(g=>g.y>-40);while(gates.length<7){const y=Math.max(...gates.map(g=>g.y),H*.55);gates.push(makeGate(y+H*.18,passed+gates.length))}
  }
  parts.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=260*dt;p.life-=dt});parts=parts.filter(p=>p.life>0);
  ctx.save();drawWorld(now);if(!shakeEnabled)shake=0;if(shake>0){ctx.translate((rng()-.5)*shake,(rng()-.5)*shake);shake*=.84}
  gates.forEach(g=>{ctx.fillStyle=g.c;ctx.shadowBlur=g.mystery?18:g.boss?15:rush>0?16:8;ctx.shadowColor=g.c;drawGateSegments(g,g.y,9);ctx.shadowBlur=0;ctx.fillStyle='#ffffff18';drawGateSegments(g,g.y+9,12);ctx.globalAlpha=.5;ctx.fillStyle='#f4f0e6';ctx.fillRect(g.gapX+g.gapW/2-1,g.y-3,2,15);ctx.globalAlpha=1;if(g.precision){const center=g.gapX+g.gapW/2,core=Math.max(6,g.gapW*.035);ctx.fillStyle='#d9ff43';ctx.shadowBlur=9;ctx.shadowColor='#d9ff43';ctx.fillRect(center-core,g.y-5,2,19);ctx.fillRect(center+core-2,g.y-5,2,19);ctx.shadowBlur=0}if(g.moving){ctx.fillStyle='#52e5ff';ctx.font='bold 8px monospace';ctx.textAlign='center';ctx.fillText('‹  ›',g.gapX+g.gapW/2,g.y-8)}if(g.shrinking){ctx.fillStyle='#ffd84a';ctx.font='bold 8px monospace';ctx.textAlign='center';ctx.fillText('›  ‹',g.gapX+g.gapW/2,g.y-8)}if(g.chain){const center=g.gapX+g.gapW/2;ctx.fillStyle='#f4f0e6';ctx.fillRect(center-8,g.y-8,3,3);ctx.fillRect(center-1,g.y-8,3,3);ctx.fillRect(center+6,g.y-8,3,3)}if(g.mystery){ctx.fillStyle='#d9ff43';ctx.font='bold 15px monospace';ctx.textAlign='center';ctx.fillText('?',g.gapX+g.gapW/2,g.y-7)}if(g.risk){ctx.fillStyle='#ffd84a';ctx.shadowBlur=12;ctx.shadowColor='#ffd84a';ctx.fillRect(g.riskX-3,g.y-5,3,19);ctx.fillRect(g.riskX+g.riskW,g.y-5,3,19);ctx.shadowBlur=0}});
  drawTrail(now);drawBall(now);updateGameStatus(now);
  parts.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,5,5)});if(flashesEnabled&&streakFlash>0){ctx.globalAlpha=Math.min(.34,streakFlash*.55);ctx.strokeStyle=combo>=50?'#ff4ea3':combo>=30?'#9b7bff':combo>=20?'#52e5ff':'#d9ff43';ctx.lineWidth=5;ctx.strokeRect(3,3,W-6,H-6);ctx.globalAlpha=1}ctx.restore();requestAnimationFrame(loop)
};
const appDisplay=matchMedia('(display-mode: standalone)').matches||matchMedia('(display-mode: fullscreen)').matches||navigator.standalone===true;
if(appDisplay){localStorage.ndInstalled='1';$('#install').hidden=true}
if(localStorage.ndInstalled==='1')$('#install').hidden=true;
addEventListener('appinstalled',()=>{localStorage.ndInstalled='1';$('#install').hidden=true});
addEventListener('beforeinstallprompt',()=>{if(localStorage.ndInstalled==='1')$('#install').hidden=true});
$('#play').addEventListener('click',()=>track('game_start',{replay:false,display_mode:appDisplay?'standalone':'browser'}));
$('#again').addEventListener('click',()=>track('game_start',{replay:true,display_mode:appDisplay?'standalone':'browser'}));
$('#install').addEventListener('click',()=>track('install_clicked'));
$('#share').addEventListener('click',()=>track('score_shared',{score,best_combo:maxCombo}));
addEventListener('appinstalled',()=>track('app_installed'));
new MutationObserver(()=>{if(!$('#over').classList.contains('hidden'))track('game_over',{score,perfects,best_combo:maxCombo,gates:passed,new_record:score===best&&score>0})}).observe($('#over'),{attributes:true,attributeFilter:['class']});
renderBoards();renderSkins();addEventListener('resize',resize);resize();requestAnimationFrame(loop);
if('serviceWorker'in navigator){const checkForUpdate=async()=>{if(!swRegistration)return;await swRegistration.update();if(swRegistration.waiting)swRegistration.waiting.postMessage('activate')};addEventListener('load',async()=>{swRegistration=await navigator.serviceWorker.register('sw.js',{updateViaCache:'none'});await checkForUpdate()});addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')checkForUpdate().catch(()=>{})});addEventListener('pageshow',()=>checkForUpdate().catch(()=>{}));setInterval(()=>checkForUpdate().catch(()=>{}),60000);navigator.serviceWorker.addEventListener('controllerchange',()=>{updatePending=true;applyUpdate()});for(const id of['play','again'])$('#'+id).addEventListener('click',event=>{if(!updatePending)return;event.preventDefault();event.stopImmediatePropagation();applyUpdate(true)},true)}
})();
